Django_quotes_13/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

Django_quotes_13/hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("forTag/<int:tag_id>", views.main, name="for_tag"),
    path("addAuthor", views.add_author, name="add_author"),
    path("addQuote", views.add_quote, name="add_quote"),
    path("addTag", views.add_tag, name="add_tag"),
    path("author/<int:author_id>", views.show_author, name="show_author"),
    path("delete/<int:author_id>", views.delete_author, name="delete_author"),
    path("delete_tag/<int:tag_id>", views.delete_tag, name="delete_tag"),
]

Django_quotes_13/hw_project/users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    # path('profile/', views.profile, name='profile'),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

Django_quotes_13/hw_project/quotes/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

Django_quotes_13/hw_project/quotes/forms.py
from django import forms
from django.forms import CharField, ModelForm, TextInput

from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    description = CharField(
        min_length=10, max_length=150, required=True, widget=TextInput()
    )
    born_date = CharField(
        min_length=6,
        max_length=50,
        required=True,
        widget=forms.DateInput(attrs={"type": "date"}),
    )
    born_location = CharField(
        min_length=4, max_length=150, required=True, widget=TextInput()
    )

    class Meta:
        model = Author
        fields = ["fullname", "description", "born_date", "born_location"]


class QuoteForm(ModelForm):
    quote = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "authors"]


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=50, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]

Django_quotes_13/hw_project/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render

from .forms import AuthorForm, QuoteForm, TagForm
# from .utils import get_mongodb
from .models import Author, Quote, Tag

# Create your views here.


def main(request, tag_id=None, page=1):
    # db = get_mongodb() # for mongodb
    # quotes = db.quotes.find() # for mongodb

    if tag_id:
        tag = get_object_or_404(Tag, id=tag_id)
        quotes = Quote.objects.filter(tags=tag)
        per_page = len(quotes)
    else:
        quotes = Quote.objects.all()
        per_page = 5

    top_tags = Tag.objects.annotate(num_quotes=Count("quote")).order_by("-num_quotes")[
        :10
    ]
    paginator = Paginator(list(quotes), per_page=per_page)
    quotes_on_page = paginator.page(page)
    return render(
        request,
        "quotes/index.html",
        context={"quotes": quotes_on_page, "top_tags": top_tags},
    )


@login_required
def add_author(request):
    authors = Author.objects.all()
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save()
            author.save()
            return redirect(to="quotes:root")
        return render(request, "quotes/author.html", {"form": form})
    return render(
        request,
        "quotes/author.html",
        context={"authors": authors, "form": AuthorForm()},
    )


@login_required
def add_quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            quote = form.save()
            author = Author.objects.filter(fullname=request.POST.get("author"))[0]
            quote.author = author
            quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                quote.tags.add(tag)
            return redirect(to="quotes:root")

        return render(
            request,
            "quotes/quote.html",
            {"form": form, "authors": authors, "tags": tags},
        )

    return render(
        request,
        "quotes/quote.html",
        context={"authors": authors, "tags": tags, "form": QuoteForm()},
    )


def show_author(request, author_id):
    author = Author.objects.get(pk=author_id)
    if author:
        return render(request, "quotes/show_author.html", context={"author": author})


@login_required
def delete_author(request, author_id):
    Author.objects.get(pk=author_id).delete()
    return redirect(to="quotes:add_author")


@login_required
def add_tag(request):
    tags = Tag.objects.all()
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save()
            tag.save()
            return redirect(to="quotes:root")
        return render(request, "quotes/tag.html", {"form": form})
    return render(
        request,
        "quotes/tag.html",
        context={"tags": tags, "form": TagForm()},
    )


@login_required
def delete_tag(request, tag_id):
    Tag.objects.get(pk=tag_id).delete()
    return redirect(to="quotes:add_tag")

Django_quotes_13/hw_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    <div>
        <h2 class="to-add">To add author</h2>
        
        {% csrf_token %}
        <div class="input">
            <label> Author name:
                {{ form.fullname }}
            </label>
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div class="input">
            <label> Author description:
                {{ form.description }}
            </label>
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="input">
            <label> Author born date:
                {{ form.born_date }}
            </label>
            <span>{{ form.errors.born_date }}</span>
        </div>
        <div class="input">
            <label> Author born location:
                {{ form.born_location }}
            </label>
            <span>{{ form.errors.born_location }}</span>
        </div>
        
        <div class="grid">
            <button class="button-sub-res" type="submit">Submit</button>
            <button class="button-sub-res" type="reset" class="secondary">Reset</button>
        </div>
        <div class="tag-container">
            {% for author in authors %}
            <div class="tag-item">
                <p class="tag-text"> {{ author.fullname }} </p>
                <a href="{% url 'quotes:delete_author' author.id %}" role="button" class="button-tag"> Delete {{author.name}} </a>
            </div>
            {% endfor %}
        </div>

    </div>
</form>

{% endblock %}

Django_quotes_13/hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>

            <div class="col-md-4">

                {% if user.is_authenticated %}

                <p>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-info" role="button">Add Quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-info" role="button">Add Author</a>
                    <a href="{% url 'quotes:add_tag' %}" class="btn btn-info" role="button">Add Tag</a>
                    <p class="badge bg-info text-wrap fs-6" style="width: 6rem;">Welcome <b>{{ user.username }}!</b></p>
                    <br>
                    <a href="{% url 'users:logout' %}" class="btn btn-info">Logout</a>
                </p>
                {% else %}
                <p>
                    <a href="{% url 'users:signup' %}" class="btn btn-info">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-info">Login</a> 
                </p>
                {% endif %}
            </div>
        </div>
    

    {% block content %} {% endblock %}
            
        
    </div>
</div>

    </div>
</body>
</html>

Django_quotes_13/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">

        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">
                {{quote.author.fullname}}
            </small>
            <a href="{% url 'quotes:show_author' quote.author.id %}">(about)</a>
            </span> 
            
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}

                <a class="tag" href="{% url 'quotes:for_tag' tag.id %}" >{{tag.name}}</a>
                
                {% endfor %}
            
        </div>
        
    </div>

    {% endfor %}

    <nav>
        <ul class="pager">
                
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">←</span> 
                Previous
            </a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next 
                <span aria-hidden="true">→</span>
            </a>
            </li>
            
        </ul>
    </nav>
    
</div>
    
<div class="col-md-2 tags-box">
    <h2 id="top-ten-tags">Top ten tags</h2>
    {% for tag in top_tags %}
    <ul class="tag-tags-box">
        <li><a href="{% url 'quotes:for_tag' tag.id %}">{{ tag.name }}</a></li>
    </ul>
    {% endfor %}
</div>
{% endblock %}

Django_quotes_13/hw_project/quotes/templates/quotes/quote.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    <div>
        <h2 class="to-add">To add quote</h2>
        
        {% csrf_token %}
        <div class="input">
            <label> Quote:
                {{ form.quote }}
            </label>
            <span>{{ form.errors.quote }}</span>
        </div>

        <div class="input">
            <label> Select tags:
                <select name="tags" multiple="multiple" required>
                    {% for tag in tags %}
                    <option value="{{tag.name}}">{{tag.name}}</option>
                    {% endfor %}
                </select>
            </label>
        </div>

        <div class="input">
            <label> Select author:
                <select name="author" multiple="multiple" required>
                    {% for author in authors %}
                    <option value="{{author.fullname}}">{{author.fullname}}</option>
                    {% endfor %}
                </select>
            </label>
        </div>
        
        <div class="grid">
            <button class="button-sub-res" type="submit">Submit</button>
            <button class="button-sub-res" type="reset" class="secondary">Reset</button>
        </div>

    </div>
</form>

{% endblock %}

Django_quotes_13/hw_project/quotes/templates/quotes/show_author.html
{% extends 'quotes/base.html' %}

{% block content %}

<div>
    <h2>{{ author.fullname }}</h2>
    <p><b>Born:</b> {{ author.born_date }}</p>
    <p><b>Description:</b><br> {{ author.description }}</p>
</div>

{% endblock %}

Django_quotes_13/hw_project/quotes/templates/quotes/tag.html
{% extends 'quotes/base.html' %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_tag' %}">
    <div>
        <h2 class="to-add">To add tag</h2>
        
        {% csrf_token %}
        <div class="input">
            <label> Tag:
                {{ form.name }}
            </label>
            <span>{{ form.errors.name }}</span>
        </div>

        <div class="grid">
            <button class="button-sub-res" type="submit">Submit</button>
            <button class="button-sub-res" type="reset" class="secondary">Reset</button>
        </div>

        <div class="tag-container">
            {% for tag in tags %}
            <div class="tag-item">
                <p class="tag-text"> {{ tag.name }} </p>
                <a href="{% url 'quotes:delete_tag' tag.id %}" role="button" class="button-tag"> Delete {{ tag.name }} </a>
            </div>
            {% endfor %}
        <div>

    </div>

{% endblock %}